"use client";

import { useEffect, useState } from "react";
import { Send, ShieldCheck } from "lucide-react";
import { AdminShell } from "@/components/admin/admin-shell";

type Persona = { slug: string; name: string };
export default function AdminCommunityPage() {
  const [personas, setPersonas] = useState<Persona[]>([]); const [personaSlug, setPersonaSlug] = useState(""); const [title, setTitle] = useState(""); const [content, setContent] = useState(""); const [category, setCategory] = useState("Discussion"); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { fetch("/api/social?kind=personas", { cache: "no-store" }).then((response) => response.json()).then((data: { items?: Persona[] }) => { const items = data.items ?? []; setPersonas(items); setPersonaSlug(items[0]?.slug ?? ""); }); }, []);
  const publish = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); setMessage(""); try { const response = await fetch("/api/social", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "admin-publish-community-post", personaSlug, title, content, category, postType: "text" }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setTitle(""); setContent(""); setMessage("Published to Community."); } catch (error) { setMessage((error as Error).message); } finally { setBusy(false); } };
  return <AdminShell title="Community Management"><div className="grid gap-6 xl:grid-cols-[1fr_.65fr]"><section className="social-card"><div className="flex items-center gap-3"><ShieldCheck className="text-cyan-300" /><div><h2 className="text-xl font-bold">Publish as an official Persona</h2><p className="mt-1 text-sm text-slate-500">Only administrators can create Persona-authored posts.</p></div></div><form onSubmit={publish} className="mt-6 space-y-4"><label className="block text-sm font-semibold">Post as<select value={personaSlug} onChange={(event) => setPersonaSlug(event.target.value)} className="social-input mt-2 w-full">{personas.map((persona) => <option key={persona.slug} value={persona.slug}>{persona.name}</option>)}</select></label><label className="block text-sm font-semibold">Category<input value={category} onChange={(event) => setCategory(event.target.value)} className="social-input mt-2 w-full" /></label><label className="block text-sm font-semibold">Title<input value={title} onChange={(event) => setTitle(event.target.value)} className="social-input mt-2 w-full" maxLength={180} /></label><label className="block text-sm font-semibold">Content<textarea required value={content} onChange={(event) => setContent(event.target.value)} className="social-input mt-2 w-full" rows={8} maxLength={20000} /></label><button disabled={busy || !personaSlug} className="social-button primary">{busy ? "Publishing..." : "Publish post"}<Send size={14} /></button>{message && <p className="text-sm text-cyan-200">{message}</p>}</form></section><section className="social-card"><p className="social-eyebrow">Management areas</p><div className="mt-4 space-y-3 text-sm text-slate-300"><p>Personas: profile and verification controls</p><p>Posts: edit, pin, schedule, and review engagement</p><p>Challenges: weekly prompts and submissions</p><p>Reports: moderation queue</p><p>Comments: replies and cleanup</p><p>Analytics: reach, likes, shares, and follows</p></div></section></div></AdminShell>;
}
