import "server-only";
import { cache } from "react";
import { getPersonaBySlug, getPersonas } from "@/lib/personas";
import { supabaseAdmin } from "@/lib/server/db";

export type PublicPersona = { slug: string; name: string; introduction: string; biography: string; profession: string; category: string; expertise: string[]; topics: string[]; disclaimer: string; avatar: string; indexable: boolean; updatedAt?: string };
export const catalogPersonas = getPersonas().filter(p => p.visibility === "Public" && p.creatorId === "system");
const text = (v: unknown) => typeof v === "string" ? v.trim() : "";
const list = (v: unknown) => (Array.isArray(v) ? v.filter((x): x is string => typeof x === "string") : text(v).split(/[,\n]/)).map(x => x.trim()).filter(Boolean).slice(0, 8);
export function publicPersonaFromRow(row: Record<string, unknown>): PublicPersona {
  // Only explicitly public presentation fields leave this server module.
  const d = row.definition && typeof row.definition === "object" ? row.definition as Record<string, unknown> : {};
  const introduction = text(row.description), expertise = list(d.expertise), topics = list(d.suggestedPrompts);
  return { slug: text(row.slug), name: text(row.name), introduction, biography: "", profession: text(d.profession) || "Community AI persona", category: text(d.category) || "Community", expertise, topics, disclaimer: "User-created AI simulation. Responses are generated by AI and can be inaccurate.", avatar: "/brand/personax-logo.svg", indexable: introduction.length >= 80 && expertise.length > 0 && topics.length >= 2, updatedAt: text(row.updated_at) || undefined };
}
export const getPublicPersona = cache(async (slug: string): Promise<PublicPersona | null> => {
  if (!/^[a-z0-9-]{1,160}$/.test(slug)) return null;
  const p = getPersonaBySlug(slug);
  if (p) return p.visibility === "Public" && p.creatorId === "system" ? { slug: p.slug, name: p.name, introduction: p.shortDescription, biography: p.biography, profession: p.profession, category: p.category, expertise: p.expertise, topics: p.suggestedPrompts, disclaimer: p.disclaimer, avatar: p.avatar || "/brand/personax-logo.svg", indexable: true } : null;
  if (!supabaseAdmin) return null;
  const { data, error } = await supabaseAdmin.from("personas").select("slug,name,description,definition,updated_at").eq("slug", slug).eq("visibility", "Public").eq("is_suspended", false).abortSignal(AbortSignal.timeout(8000)).maybeSingle();
  if (error) throw new Error("Public persona lookup unavailable");
  return data ? publicPersonaFromRow(data) : null;
});
export const SITEMAP_BATCH_SIZE = 1000;
export async function countPublicCommunityPersonas() {
  if (!supabaseAdmin) return 0;
  const { count, error } = await supabaseAdmin.from("personas").select("slug", { count: "exact", head: true }).eq("visibility", "Public").eq("is_suspended", false).abortSignal(AbortSignal.timeout(8000));
  if (error) throw new Error("Public sitemap lookup unavailable");
  return count ?? 0;
}
export async function publicCommunityBatch(page: number) {
  if (!supabaseAdmin) return [];
  const { data, error } = await supabaseAdmin.from("personas").select("slug,name,description,definition,updated_at").eq("visibility", "Public").eq("is_suspended", false).order("slug").range(page * SITEMAP_BATCH_SIZE, (page + 1) * SITEMAP_BATCH_SIZE - 1).abortSignal(AbortSignal.timeout(8000));
  if (error) throw new Error("Public sitemap lookup unavailable");
  const known = new Set(catalogPersonas.map(p => p.slug));
  return (data ?? []).map(publicPersonaFromRow).filter(p => p.indexable && /^[a-z0-9-]{1,160}$/.test(p.slug) && !known.has(p.slug));
}
