"use client";
import Link from 'next/link';
import {useState,useSyncExternalStore} from 'react';
import {Heart,UserPlus,Share2,Globe,Lock,Star} from 'lucide-react';
import {getCurrentUser,subscribeToAuth} from '@/lib/auth';
import {socialRequest,number,type PersonaSocial} from '@/lib/social';
import type {CustomPersona} from '@/lib/custom-personas';
import {useSocial} from './common';

export function SocialToggle({action,target,active,count,label,onChange}:{action:string;target:string;active:boolean;count?:number;label:string;onChange:()=>void}) {
 const [busy,setBusy]=useState(false),[error,setError]=useState('');
 async function toggle(){setBusy(true);setError('');try{await socialRequest({action,target,active:!active});onChange();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <span className="inline-flex flex-col items-start gap-1"><button type="button" className={`social-button ${active?'selected':''}`} aria-pressed={active} disabled={busy} onClick={toggle}>{action.includes('like')?<Heart size={15} fill={active?'currentColor':'none'}/>:<UserPlus size={15}/>} {active?(action.includes('like')?'Liked':'Following'):label}{count!==undefined&&<span className="opacity-70">{number(count)}</span>}</button>{error&&<span role="alert" className="max-w-64 text-xs text-rose-300">{error}</span>}</span>;
}
export function ShareToProfile(props:{submissionId?:string;personaSlug?:string;question?:string;answer?:string;sourceKey?:string}) {
 const [done,setDone]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function share(){setBusy(true);setError('');try{await socialRequest({action:'share',...props});setDone(true);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <span className="inline-flex flex-col items-start gap-1"><button type="button" className="social-button small" title="Publish only this question and answer to your public profile" disabled={done||busy} onClick={share}><Share2 size={13}/>{done?'Shared to Profile':busy?'Sharing…':'Share to Profile'}</button>{done&&<Link href="/creators/me" className="text-xs text-cyan-300">View profile →</Link>}{error&&<span role="alert" className="text-xs text-rose-300">{error}</span>}</span>;
}
export function PersonaSocialPanel({slug}:{slug:string}) {
 const {data:p,error,loading,reload}=useSocial<PersonaSocial>(`kind=persona&slug=${encodeURIComponent(slug)}`,true);
 const [notice,setNotice]=useState('');
 async function rate(rating:number){try{await socialRequest({action:'rate',target:slug,rating});setNotice('Rating saved. Averages refresh every 5 minutes.');}catch(e){setNotice((e as Error).message);}}
 if(loading)return <div className="social-card my-6 text-sm text-slate-400">Loading community stats…</div>;
 if(error||!p)return <div className="social-card my-6 text-sm text-slate-400">{error}<button className="ml-3 text-cyan-300" onClick={reload}>Retry</button></div>;
 return <section className="social-card my-6"><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><p className="social-eyebrow">Community impact</p>{p.creator_id&&p.username?<Link href={`/creators/${p.username}`} className="text-sm text-cyan-300">View Creator Profile · @{p.username} ↗</Link>:<span className="text-xs text-slate-500">SOULX original</span>}</div><div className="social-stats compact">{[['Unique users',number(p.unique_users)],['Total chats',number(p.conversations)],['Fans worldwide',number(p.likes)],['Followers',number(p.followers)],['Rating',p.rating?`${p.rating.toFixed(1)} / 5`:'Unrated'],['Weekly rank',p.weekly_rank?`#${p.weekly_rank}`:'—'],['All-time rank',p.all_rank?`#${p.all_rank}`:'—'],['Trending',p.trending_score>0?'Rising ↗':'Building']].map(([label,value])=><div key={label}><strong>{value}</strong><span>{label}</span></div>)}</div><div className="mt-5 flex flex-wrap items-start gap-2"><SocialToggle action="like" target={slug} active={!!p.liked} label="Like" onChange={reload}/><SocialToggle action="follow-persona" target={slug} active={!!p.followed} label="Follow Persona" onChange={reload}/><label className="social-button"><Star size={14}/><select aria-label="Rate this Persona" defaultValue="" onChange={e=>void rate(Number(e.target.value))} className="bg-slate-950 text-sm"><option value="" disabled>Rate Persona</option>{[1,2,3,4,5].map(n=><option value={n} key={n}>{n} stars</option>)}</select></label></div>{notice&&<p className="mt-3 text-xs text-cyan-200" role="status">{notice}</p>}</section>;
}
export function PublishPersona({persona}:{persona:CustomPersona}) {
 const [busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function publish(isPublic:boolean){setBusy(true);setMessage('');try{await socialRequest({action:'publish-persona',persona,public:isPublic});setMessage(isPublic?'Published to the community.':'Persona is now private.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 return <div className="mt-4 border-t border-white/10 pt-4"><p className="mb-3 text-xs text-slate-500">Publish your saved Persona to build an audience.</p><div className="flex flex-wrap gap-2"><button disabled={busy} type="button" className="social-button small" onClick={()=>publish(true)}><Globe size={13}/>Publish / update public</button><button disabled={busy} type="button" className="social-button small" onClick={()=>publish(false)}><Lock size={13}/>Make private</button><Link className="social-button small" href={`/persona/${persona.id}`}>Public page ↗</Link></div>{message&&<p role="status" className="mt-2 text-xs text-cyan-200">{message}</p>}<ChallengePublisher slug={persona.id}/></div>;
}
export function MyCreatorLink(){const user=useSyncExternalStore(subscribeToAuth,getCurrentUser,()=>null);return user?<Link href="/creators/me" className="social-button my-4"><Globe size={15}/>My public creator profile ↗</Link>:null;}
function ChallengePublisher({slug}:{slug:string}) {
 const [open,setOpen]=useState(false),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);setBusy(true);try{await socialRequest({action:'publish-challenge',target:slug,question:form.get('question'),expectedAnswer:form.get('expectedAnswer'),difficulty:form.get('difficulty'),category:form.get('category'),xpReward:Number(form.get('xpReward'))});setMessage('Weekly challenge published.');setOpen(false);}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 return <div className="mt-3"><button type="button" className="text-xs text-cyan-300" onClick={()=>setOpen(!open)}>Publish a weekly challenge</button>{open&&<form onSubmit={submit} className="mt-3 space-y-3"><p className="text-xs text-slate-500">Available for selected Personas. One challenge per week; closes Monday at 00:00 UTC.</p><label className="block text-xs">Question<textarea required name="question" minLength={10} maxLength={4000} className="social-input mt-1"/></label><label className="block text-xs">Private answer key / grading rubric<textarea required name="expectedAnswer" minLength={5} maxLength={8000} className="social-input mt-1"/></label><div className="grid grid-cols-2 gap-2"><label className="text-xs">Difficulty<select name="difficulty" className="social-input">{['Easy','Medium','Hard'].map(s=><option key={s}>{s}</option>)}</select></label><label className="text-xs">Category<select name="category" className="social-input">{['General','Science','Logic','Business','Writing'].map(s=><option key={s}>{s}</option>)}</select></label></div><label className="block text-xs">XP reward<input name="xpReward" type="number" min={10} max={500} defaultValue={100} required className="social-input"/></label><button disabled={busy} className="social-button">{busy?'Publishing…':'Publish challenge'}</button></form>}{message&&<p role="status" className="mt-2 text-xs text-cyan-200">{message}</p>}</div>;
}
