import { redirect } from "next/navigation";

export default function ChallengesPage() {
	redirect("/community?tab=challenges");
}

/*
"use client";
import {useState} from 'react';
import {Brain,Clock,Users,Zap,ArrowUpRight,ShieldCheck} from 'lucide-react';
import {Avatar,Feedback,SocialHero,useSocial} from '@/components/social/common';
import {socialRequest,type Challenge,type Submission} from '@/lib/social';
import {ShareToProfile} from '@/components/social/controls';

function ChallengeCard({challenge:c}:{challenge:Challenge}) {
 const [open,setOpen]=useState(false),[answer,setAnswer]=useState(''),[result,setResult]=useState<Submission|null>(c.submission??null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{setResult(await socialRequest<Submission>({action:'submit',target:c.id,answer}));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <article className="social-challenge"><div className="flex items-center gap-3"><Avatar src={c.avatar} name={c.name}/><div><p className="font-semibold">{c.name}</p><p className="mt-1 text-xs text-slate-500">{c.category} challenge</p></div><span className={`social-difficulty ${c.difficulty.toLowerCase()}`}>{c.difficulty}</span></div><h2>{c.question}</h2><div className="social-challenge-meta"><span><Zap size={15}/>{c.xp_reward} XP</span><span><Users size={14}/>{c.participants} participants</span></div><p className="my-5 flex gap-2 text-xs text-slate-400"><Clock size={14}/>Ends {new Date(c.deadline).toLocaleString(undefined,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit',timeZoneName:'short'})}</p>
 {result?<div className="social-result" role="status"><div className="flex items-center justify-between"><strong>{result.score??'…'}<small>/100</small></strong><span className="social-pill">+{result.xp_earned} XP</span></div><p className="mt-2 font-semibold capitalize">{result.status}</p><p className="my-3 text-sm leading-6 text-slate-300">{result.feedback}</p>{result.score!==null&&<ShareToProfile submissionId={result.id}/>}</div>:open?<form onSubmit={submit}><label htmlFor={`answer-${c.id}`} className="text-sm text-slate-300">Your answer</label><textarea id={`answer-${c.id}`} value={answer} onChange={e=>setAnswer(e.target.value)} maxLength={12000} required rows={5} className="social-input mt-2" placeholder="Show your reasoning…"/><p className="my-3 text-xs text-slate-500">One submission per challenge. AI feedback and XP appear after you submit.</p><button className="social-button primary w-full" disabled={busy||!answer.trim()}>{busy?'Evaluating your answer…':'Submit answer'}<ArrowUpRight size={15}/></button></form>:<button className="social-button primary w-full" onClick={()=>setOpen(true)}>Accept challenge <ArrowUpRight size={15}/></button>}{error&&<p role="alert" className="mt-3 text-sm text-rose-300">{error}</p>}</article>;
}
export default function ChallengesPage(){const [page,setPage]=useState(0);const {data,error,loading,reload}=useSocial<{items:Challenge[]}>(`kind=challenges&page=${page}`);return <main className="social-page"><SocialHero eyebrow="A little curiosity. A new possibility." title="Challenge your perspective." description="A fresh question from an extraordinary mind. Put your thinking to the test and turn insight into XP."><div className="social-hero-emblem violet"><Brain size={64} strokeWidth={1}/><span>WEEKLY CHALLENGES</span></div></SocialHero><div className="social-toolbar"><h2 className="text-xl font-semibold">This week’s challenges</h2><span className="social-pill"><Zap size={14}/>Learn · Solve · Level up</span></div><Feedback loading={loading} error={error} retry={reload}/>{data&&!loading&&!error&&<>{data.items.length?<div className="grid items-start gap-5 md:grid-cols-2 xl:grid-cols-3">{data.items.map(c=><ChallengeCard key={c.id} challenge={c}/>)}</div>:<div className="social-empty"><Brain size={32}/><h2>A new challenge is on the horizon</h2><p>Selected Personas publish new questions each week. Check back for the next round.</p></div>}<div className="social-pagination"><button className="social-button" disabled={!page} onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {page+1}</span><button className="social-button" disabled={data.items.length<24} onClick={()=>setPage(p=>p+1)}>Next</button></div></>}<div className="social-card mt-8 flex gap-4"><ShieldCheck className="shrink-0 text-cyan-300"/><p className="text-sm leading-6 text-slate-400">Your submission is private. Only an answer you explicitly share to your profile becomes public. XP is proportional to your score; answer keys stay hidden.</p></div></main>;}
*/
