"use client";
import Link from 'next/link';
import {useParams} from 'next/navigation';
import {useState} from 'react';
import {Award,ShieldCheck,Zap,Globe,Settings2} from 'lucide-react';
import {Avatar,Feedback,PersonaCard,useSocial} from '@/components/social/common';
import {SocialToggle} from '@/components/social/controls';
import {socialRequest,number,type Creator} from '@/lib/social';

export default function CreatorPage(){
 const {username}=useParams<{username:string}>();const [page,setPage]=useState(0),[tab,setTab]=useState('personas'),[notice,setNotice]=useState('');
 const {data:p,error,loading,reload}=useSocial<Creator>(`kind=profile&username=${encodeURIComponent(username)}&page=${page}`,true);
 async function changeUsername(e:React.FormEvent<HTMLFormElement>){e.preventDefault();try{await socialRequest({action:'profile',username:new FormData(e.currentTarget).get('username')});setNotice('Username updated.');reload();}catch(e){setNotice((e as Error).message);}}
 async function unshare(id:string){try{await socialRequest({action:'unshare',target:id});reload();}catch(e){setNotice((e as Error).message);}}
 return <main className="social-page"><Feedback loading={loading} error={error} retry={reload}/>{p&&!loading&&!error&&<><section className="social-profile"><div className="social-profile-cover"><span className="social-eyebrow">SOULX / CREATOR</span><Globe size={100} strokeWidth={0.5}/></div><div className="social-profile-body"><div className="flex flex-wrap items-end justify-between gap-4"><Avatar src={p.avatar_data_url} name={p.display_name} size="profile"/><div className="flex flex-wrap gap-2">{p.is_owner?<Link className="social-button" href="/profile"><Settings2 size={15}/>Edit profile</Link>:<SocialToggle action="follow-creator" target={p.user_id} active={p.followed} count={p.followers} label="Follow creator" onChange={reload}/>}<Link className="social-button" href="/leaderboard">Leaderboard ↗</Link></div></div><div className="mt-6 flex flex-wrap items-center gap-3"><h1 className="text-3xl font-bold tracking-tight sm:text-4xl">{p.display_name}</h1><span className="social-pill"><Zap size={13}/>Level {p.level}</span></div><p className="mt-2 text-sm text-cyan-300">@{p.username}</p><p className="mt-4 max-w-2xl text-sm leading-7 text-slate-400">{p.bio||'A curious mind. A world of possibilities.'}</p><div className="mt-5 flex flex-wrap gap-5 text-sm"><span><b>{number(p.followers)}</b> <span className="text-slate-400">followers</span></span><span><b>{number(p.following)}</b> <span className="text-slate-400">following</span></span></div><div className="mt-6 max-w-md"><div className="mb-2 flex justify-between text-xs text-slate-400"><span>{number(p.xp)} total XP</span><span>Level {p.level+1} at {number(p.level*p.level*100)} XP</span></div><progress className="social-progress" value={p.xp-(p.level-1)**2*100} max={(p.level**2-(p.level-1)**2)*100}/></div>{p.is_owner&&<details className="mt-5 text-xs text-slate-400"><summary className="cursor-pointer">Public profile settings</summary><p className="my-3">Your profile is {p.profile_visibility.toLowerCase()}. Update your bio, photo and visibility in Edit profile.</p><form onSubmit={changeUsername} className="flex max-w-md gap-2"><input aria-label="Public username" name="username" required defaultValue={p.username} className="social-input"/><button className="social-button">Save username</button></form></details>}</div></section>
 <section className="social-stats my-6">{[['Personas created',p.persona_count],['Persona users',p.persona_users],['Persona likes',p.persona_likes],['Weekly rank',p.weekly_rank?`#${p.weekly_rank}`:'—'],['All-time rank',p.all_rank?`#${p.all_rank}`:'—']].map(([label,value])=><div key={label}><strong>{typeof value==='number'?number(value):value}</strong><span>{label}</span></div>)}</section>
 <div className="social-toolbar"><div className="social-tabs" role="tablist" aria-label="Creator content"><button role="tab" aria-selected={tab==='personas'} onClick={()=>{setTab('personas');setPage(0);}}>Created Personas</button><button role="tab" aria-selected={tab==='answers'} onClick={()=>{setTab('answers');setPage(0);}}>Best Answers</button></div><span className="flex items-center gap-2 text-xs text-slate-500"><ShieldCheck size={14}/>Shared by choice</span></div>
 {tab==='personas'?p.personas.length?<div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{p.personas.map(persona=><PersonaCard key={persona.slug} p={persona}/>)}</div>:<div className="social-empty">No public Personas yet.{p.is_owner&&<Link className="social-button primary" href="/create">Create a Persona →</Link>}</div>:p.answers.length?<div className="grid items-start gap-5 md:grid-cols-2">{p.answers.map(a=><article key={a.id} className="social-card"><div className="flex items-center gap-3"><Avatar src={p.avatar_data_url} name={p.display_name}/><div><p className="text-sm font-semibold">{p.display_name} <span className="font-normal text-slate-500">with {a.persona_name}</span></p><time className="text-xs text-slate-500">{new Date(a.created_at).toLocaleDateString()}</time></div>{a.score!=null&&<span className="social-pill ml-auto">{a.score}/100</span>}</div><h3 className="my-4 font-semibold">{a.question}</h3><p className="whitespace-pre-wrap break-words text-sm leading-7 text-slate-300">{a.answer}</p><div className="mt-5 flex flex-wrap items-start gap-3"><SocialToggle action="like-answer" target={a.id} active={a.liked} label="Like" count={a.likes} onChange={reload}/>{p.is_owner&&<button className="social-button" onClick={()=>unshare(a.id)}>Remove from profile</button>}</div></article>)}</div>:<div className="social-empty"><ShieldCheck size={26}/><p>No answers shared yet. Conversations stay private unless an answer is explicitly shared.</p></div>}
 <div className="social-pagination"><button className="social-button" disabled={!page} onClick={()=>setPage(n=>n-1)}>Previous</button><span>Page {page+1}</span><button className="social-button" disabled={(tab==='personas'?p.personas:p.answers).length<24} onClick={()=>setPage(n=>n+1)}>Next</button></div>{notice&&<p role="status" className="text-sm text-cyan-200">{notice}</p>}</>}</main>;
}
