"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { KeyRound, ShieldCheck } from "lucide-react";
export default function AdminLoginPage() {
  const router=useRouter(); const [email,setEmail]=useState(""),[password,setPassword]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
  async function submit(event:React.FormEvent){event.preventDefault();setBusy(true);setError("");try{const response=await fetch("/api/admin/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,password}),credentials:"same-origin"});const data=await response.json();if(!response.ok)throw new Error(data.error);router.replace("/admin");router.refresh();}catch(error){setError(error instanceof Error?error.message:"Login failed.");}finally{setBusy(false);}}
  return <main className="mx-auto flex min-h-[70vh] max-w-md items-center px-4 py-12 text-white"><section className="w-full rounded-[30px] border border-cyan-300/20 bg-slate-950/85 p-7 shadow-[0_25px_90px_rgba(2,8,23,.6)]"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl border border-cyan-300/25 bg-cyan-400/10 text-cyan-300"><KeyRound/></div><p className="mt-6 text-center text-xs font-bold uppercase tracking-[.25em] text-cyan-300">Restricted area</p><h1 className="mt-3 text-center text-3xl font-black">SOULX control center</h1><p className="mt-3 text-center text-sm leading-6 text-slate-400">Sign in with the administrator account configured on the server.</p><form onSubmit={submit} className="mt-7 space-y-4"><label className="block text-sm">Admin email<input required type="email" autoComplete="username" value={email} onChange={e=>setEmail(e.target.value)} className="social-input mt-2"/></label><label className="block text-sm">Password<input required type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} className="social-input mt-2"/></label>{error&&<p role="alert" className="rounded-xl border border-rose-300/20 bg-rose-400/10 p-3 text-sm text-rose-200">{error}</p>}<button disabled={busy} className="social-button primary w-full"><ShieldCheck size={16}/>{busy?"Verifying…":"Sign in securely"}</button></form><p className="mt-6 text-center text-[11px] text-slate-500">Credentials are checked server-side and never stored in the browser.</p></section></main>;
}
