"use client";
import Link from 'next/link';
import { useEffect,useState,useCallback } from 'react';
import { ArrowUpRight,Flame,Heart,Users,RefreshCw,Sparkles } from 'lucide-react';
import { socialRequest,number,type PersonaSocial } from '@/lib/social';

export function useSocial<T>(params:string,live=false) {
  const [data,setData]=useState<T|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true);
  const reload=useCallback(async()=>{try{const next=await socialRequest<T>(params);setData(next);setError('');}catch(e){setError((e as Error).message);}finally{setLoading(false);}},[params]);
  useEffect(()=>{let active=true;socialRequest<T>(params).then(d=>{if(active)setData(d);}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});const id=live?setInterval(()=>{if(document.visibilityState==='visible')void reload();},15000):undefined;return()=>{active=false;clearInterval(id);};},[params,live,reload]);
  return {data,error,loading,reload};
}
export function Avatar({src,name,size=''}:{src?:string;name:string;size?:string}) {return src?<img src={src} alt="" className={`social-avatar ${size}`}/>:<span className={`social-avatar ${size}`}>{name?.slice(0,2).toUpperCase()||'PX'}</span>;}
export function Feedback({loading,error,retry}:{loading:boolean;error:string;retry:()=>void}) {return loading?<div className="social-empty" role="status"><Sparkles className="animate-pulse"/>Loading community…</div>:error?<div className="social-empty" role="alert"><p>{error}</p><button onClick={retry} className="social-button"><RefreshCw size={14}/>Try again</button></div>:null;}
export function SocialHero({eyebrow,title,description,children}:{eyebrow:string;title:string;description:string;children?:React.ReactNode}) {return <header className="social-hero"><div><p className="social-eyebrow"><span/>{eyebrow}</p><h1>{title}</h1><p className="social-description">{description}</p><nav className="social-links" aria-label="Community"><Link href="/leaderboard">Leaderboard <ArrowUpRight size={14}/></Link><Link href="/challenges">Weekly challenges <ArrowUpRight size={14}/></Link><Link href="/creators/me">My creator profile <ArrowUpRight size={14}/></Link></nav></div>{children}</header>;}
export function PersonaCard({p}:{p:PersonaSocial}) {return <article className="social-card"><div className="flex items-center gap-3"><Avatar src={p.avatar} name={p.name}/><div className="min-w-0"><Link className="font-bold" href={`/persona/${p.slug}`}>{p.name}</Link><p className="text-xs text-slate-400">{p.username?`by @${p.username}`:'SOULX original'}</p></div>{p.trending_score>0&&<Flame size={18} className="ml-auto text-amber-300"/>}</div><p className="my-4 line-clamp-2 text-sm leading-6 text-slate-400">{p.description}</p><div className="flex items-center gap-4 text-xs text-slate-400"><span className="flex gap-1.5"><Users size={14}/>{number(p.unique_users)}</span><span className="flex gap-1.5"><Heart size={14}/>{number(p.likes)} fans worldwide</span><Link href={`/persona/${p.slug}`} className="ml-auto text-cyan-300">Explore →</Link></div></article>;}
export function TrendingPersonas({community=false}:{community?:boolean}) {const {data,error,loading,reload}=useSocial<{items:PersonaSocial[]}>(`kind=${community?'personas':'trending'}`);return <section className="my-8"><div className="mb-5 flex items-center justify-between"><div><p className="social-eyebrow">{community?'Made by the community':'The conversation is growing'}</p><h2 className="mt-2 text-2xl font-bold">{community?'Community Personas':'Trending Personas'} <span className="text-cyan-300">↗</span></h2></div><Link className="text-sm text-slate-400" href="/leaderboard">View leaderboard →</Link></div><Feedback loading={loading} error={error} retry={reload}/>{data&&<>{data.items.length?<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{data.items.slice(0,6).map(p=><PersonaCard key={p.slug} p={p}/>)}</div>:<div className="social-empty">{community?'Publish a Persona to start building your audience.':'The next rising Persona could be yours. Recent community activity will appear here.'}</div>}</>}</section>;}
